SHOW DATABASES;
USE world;
SHOW TABLES;
SHOW TABLE STATUS;
DESC country;
SELECT * FROM city;
SELECT Name,Population FROM city;
SELECT Name,Population FROM city WHERE Population>5000000;
SELECT Name,Population FROM city WHERE Countrycode='USA';
SELECT Name,Population FROM city WHERE Population BETWEEN 127800 AND 130000;
SELECT Population FROM city WHERE Name IN('seoul','pusan');
SELECT * FROM city WHERE Name LIKE '%city';
SELECT * FROM city WHERE CountryCode IN ('KOR') AND Name LIKE '%san';
SELECT * FROM city WHERE District LIKE 'Kyong%';
SELECT * FROM city WHERE Name LIKE '%won%';
SELECT * FROM city WHERE District = (SELECT District FROM city WHERE NAME='suwon');
SELECT * FROM city WHERE Population > ANY (SELECT Population FROM city WHERE District='Kyonggi');
SELECT * FROM city WHERE Population > ALL (SELECT Population FROM city WHERE District='Kyonggi');
SELECT * FROM city WHERE District = 'Kyonggi' ORDER BY Population ASC;
SELECT * FROM city WHERE District = 'Kyonggi' ORDER BY NAME ASC;
SELECT DISTINCT Name,Countrycode FROM city;
SELECT Name FROM city ORDER BY population DESC LIMIT 15;
SELECT Name AS "CN" FROM city GROUP BY CountryCode;
SELECT CountryCode, SUM(Population) FROM city GROUP BY CountryCode;
SELECT CountryCode, SUM(Population) AS "COUNTRY POPULATION" FROM city GROUP BY CountryCode;
SELECT COUNT(*) FROM city;
SELECT CountryCode,SUM(Population) AS "TOTAL POPULATION" FROM city GROUP BY CountryCode HAVING SUM(Population)>25000000;
SELECT CountryCode,Name,SUM(Population) FROM city GROUP BY CountryCode,Name WITH ROLLUP;
SELECT CountryCode,Name,SUM(Population) FROM city GROUP BY CountryCode,Name WITH ROLLUP HAVING SUM(Population)>1000000;
SELECT * FROM city JOIN country;
SELECT * FROM city JOIN country ON city.Countrycode=country.Code;
SELECT * FROM city JOIN country ON city.Countrycode=country.Code JOIN countrylanguage ON city.CountryCode = countrylanguage.Countrycode;
SELECT LENGTH('123456');
SELECT CONCAT('A','B','C',NULL);
SELECT LOCATE('a','b');
SELECT LEFT('abc',2);
SELECT RIGHT('abc','2');
SELECT LOWER('ABC');
SELECT UPPER('abc');
SELECT UPPER('ASDAsdakdwka');
SELECT REPLACE('PYTHON3','THON','PY');
SELECT TRIM(' HELLO~ ');
SELECT TRIM('HEL LO');
SELECT FORMAT(100000000.11111,3);
SELECT FORMAT(10000000.3456,3);
SELECT CEIL(1.7), FLOOR(1.7), ROUND(1.7);
SELECT SQRT(1.2),EXP(9),POW(2,3);
SELECT SIN(pi()/2);
SELECT RAND();
SELECT NOW(),CURDATE(),CURTIME();